package com.xeraster.supertnt;

import com.google.common.base.Preconditions;
import com.xeraster.supertnt.blocks.BlockCheeseBlock;
import com.xeraster.supertnt.blocks.BlockCheeseBush;
import com.xeraster.supertnt.blocks.BlockCheeseGrass;
import com.xeraster.supertnt.blocks.BlockCheeseLeaves;
import com.xeraster.supertnt.blocks.BlockCrapGrass;
import com.xeraster.supertnt.blocks.BlockEyeLol;
import com.xeraster.supertnt.blocks.BlockFluidPoop;
import com.xeraster.supertnt.blocks.BlockGayLeaves;
import com.xeraster.supertnt.blocks.BlockGayPlant;
import com.xeraster.supertnt.blocks.BlockGlassDiamond;
import com.xeraster.supertnt.blocks.BlockMouthLol;
import com.xeraster.supertnt.blocks.BlockNoAnswer;
import com.xeraster.supertnt.blocks.BlockPoopLeaves;
import com.xeraster.supertnt.blocks.BlockPoopPlant;
import com.xeraster.supertnt.blocks.BlockSolidPoop;
import com.xeraster.supertnt.blocks.BlockTNTAirborne;
import com.xeraster.supertnt.blocks.BlockTNTArrow;
import com.xeraster.supertnt.blocks.BlockTNTBiome;
import com.xeraster.supertnt.blocks.BlockTNTBunker;
import com.xeraster.supertnt.blocks.BlockTNTCave;
import com.xeraster.supertnt.blocks.BlockTNTCheese;
import com.xeraster.supertnt.blocks.BlockTNTChristmas;
import com.xeraster.supertnt.blocks.BlockTNTCluster;
import com.xeraster.supertnt.blocks.BlockTNTCrack;
import com.xeraster.supertnt.blocks.BlockTNTCrap;
import com.xeraster.supertnt.blocks.BlockTNTCrap2;
import com.xeraster.supertnt.blocks.BlockTNTDiamond;
import com.xeraster.supertnt.blocks.BlockTNTDiamondNuke;
import com.xeraster.supertnt.blocks.BlockTNTDoom;
import com.xeraster.supertnt.blocks.BlockTNTEnd;
import com.xeraster.supertnt.blocks.BlockTNTEverything;
import com.xeraster.supertnt.blocks.BlockTNTFact;
import com.xeraster.supertnt.blocks.BlockTNTFire;
import com.xeraster.supertnt.blocks.BlockTNTFlat;
import com.xeraster.supertnt.blocks.BlockTNTForest;
import com.xeraster.supertnt.blocks.BlockTNTHell;
import com.xeraster.supertnt.blocks.BlockTNTHouse;
import com.xeraster.supertnt.blocks.BlockTNTIsland;
import com.xeraster.supertnt.blocks.BlockTNTJail;
import com.xeraster.supertnt.blocks.BlockTNTKimJong;
import com.xeraster.supertnt.blocks.BlockTNTLGBT;
import com.xeraster.supertnt.blocks.BlockTNTLarge;
import com.xeraster.supertnt.blocks.BlockTNTLava;
import com.xeraster.supertnt.blocks.BlockTNTLavaOcean;
import com.xeraster.supertnt.blocks.BlockTNTMassive;
import com.xeraster.supertnt.blocks.BlockTNTMine;
import com.xeraster.supertnt.blocks.BlockTNTMob;
import com.xeraster.supertnt.blocks.BlockTNTMob2;
import com.xeraster.supertnt.blocks.BlockTNTMob3;
import com.xeraster.supertnt.blocks.BlockTNTNoMob;
import com.xeraster.supertnt.blocks.BlockTNTNostalgia;
import com.xeraster.supertnt.blocks.BlockTNTOcean;
import com.xeraster.supertnt.blocks.BlockTNTPleaseNo;
import com.xeraster.supertnt.blocks.BlockTNTRake;
import com.xeraster.supertnt.blocks.BlockTNTSave;
import com.xeraster.supertnt.blocks.BlockTNTSingularity;
import com.xeraster.supertnt.blocks.BlockTNTSnow;
import com.xeraster.supertnt.blocks.BlockTNTSponge;
import com.xeraster.supertnt.blocks.BlockTNTSuper;
import com.xeraster.supertnt.blocks.BlockTNTSuperCluster;
import com.xeraster.supertnt.blocks.BlockTNTTeleport;
import com.xeraster.supertnt.blocks.BlockTNTThunder;
import com.xeraster.supertnt.blocks.BlockTNTTime;
import com.xeraster.supertnt.blocks.BlockTNTTinyIsland;
import com.xeraster.supertnt.blocks.BlockTNTTree;
import com.xeraster.supertnt.blocks.BlockTNTTrump;
import com.xeraster.supertnt.blocks.BlockTNTWarp;
import com.xeraster.supertnt.blocks.BlockTNTWave;
import com.xeraster.supertnt.blocks.BlockTNTWeather;
import com.xeraster.supertnt.blocks.BlockTNTWeed;
import com.xeraster.supertnt.blocks.BlockTNTWtf;
import com.xeraster.supertnt.blocks.BlockTestBlock;
import com.xeraster.supertnt.blocks.BlockYesAnswer;
import com.xeraster.supertnt.fluids.ModFluid;
import com.xeraster.supertnt.fluids.ModMaterials;
import com.xeraster.supertnt.primedtnt.EntityTNTAirbornePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTArrowPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTBiomePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTBunkerPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTCavePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTCheesePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTChristmasPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTClusterPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTCrackPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTCrap2Primed;
import com.xeraster.supertnt.primedtnt.EntityTNTCrapPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTDiamondNukePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTDiamondPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTDoomPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTEndPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTEverythingPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTFactPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTFirePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTFlatPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTForestPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTHellPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTHousePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTIslandPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTJailPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTKimJongPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTLGBTPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTLargePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTLavaOceanPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTLavaPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTMassivePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTMinePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTMob2Primed;
import com.xeraster.supertnt.primedtnt.EntityTNTMob3Primed;
import com.xeraster.supertnt.primedtnt.EntityTNTMobPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTNoMobPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTNostalgiaPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTOceanPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTPleaseNoPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTRakePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSavePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSingularityPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSnowPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSpongePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSuperClusterPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTSuperPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTTeleportPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTThunderPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTTimePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTTinyIslandPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTTreePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTTrumpPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTWarpPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTWavePrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTWeatherPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTWeedPrimed;
import com.xeraster.supertnt.primedtnt.EntityTNTWtfPrimed;
import com.xeraster.supertnt.renders.RenderTNTAirbornePrimed;
import com.xeraster.supertnt.renders.RenderTNTArrowPrimed;
import com.xeraster.supertnt.renders.RenderTNTBiomePrimed;
import com.xeraster.supertnt.renders.RenderTNTBunkerPrimed;
import com.xeraster.supertnt.renders.RenderTNTCavePrimed;
import com.xeraster.supertnt.renders.RenderTNTCheesePrimed;
import com.xeraster.supertnt.renders.RenderTNTChristmasPrimed;
import com.xeraster.supertnt.renders.RenderTNTClusterPrimed;
import com.xeraster.supertnt.renders.RenderTNTCrackPrimed;
import com.xeraster.supertnt.renders.RenderTNTCrap2Primed;
import com.xeraster.supertnt.renders.RenderTNTCrapPrimed;
import com.xeraster.supertnt.renders.RenderTNTDiamondNukePrimed;
import com.xeraster.supertnt.renders.RenderTNTDiamondPrimed;
import com.xeraster.supertnt.renders.RenderTNTDoomPrimed;
import com.xeraster.supertnt.renders.RenderTNTEndPrimed;
import com.xeraster.supertnt.renders.RenderTNTEverythingPrimed;
import com.xeraster.supertnt.renders.RenderTNTFactPrimed;
import com.xeraster.supertnt.renders.RenderTNTFirePrimed;
import com.xeraster.supertnt.renders.RenderTNTFlatPrimed;
import com.xeraster.supertnt.renders.RenderTNTForestPrimed;
import com.xeraster.supertnt.renders.RenderTNTHellPrimed;
import com.xeraster.supertnt.renders.RenderTNTHousePrimed;
import com.xeraster.supertnt.renders.RenderTNTIslandPrimed;
import com.xeraster.supertnt.renders.RenderTNTJailPrimed;
import com.xeraster.supertnt.renders.RenderTNTKimJongPrimed;
import com.xeraster.supertnt.renders.RenderTNTLGBTPrimed;
import com.xeraster.supertnt.renders.RenderTNTLargePrimed;
import com.xeraster.supertnt.renders.RenderTNTLavaOceanPrimed;
import com.xeraster.supertnt.renders.RenderTNTLavaPrimed;
import com.xeraster.supertnt.renders.RenderTNTMassivePrimed;
import com.xeraster.supertnt.renders.RenderTNTMinePrimed;
import com.xeraster.supertnt.renders.RenderTNTMob2Primed;
import com.xeraster.supertnt.renders.RenderTNTMob3Primed;
import com.xeraster.supertnt.renders.RenderTNTMobPrimed;
import com.xeraster.supertnt.renders.RenderTNTNoMobPrimed;
import com.xeraster.supertnt.renders.RenderTNTNostalgiaPrimed;
import com.xeraster.supertnt.renders.RenderTNTOceanPrimed;
import com.xeraster.supertnt.renders.RenderTNTPleaseNoPrimed;
import com.xeraster.supertnt.renders.RenderTNTRakePrimed;
import com.xeraster.supertnt.renders.RenderTNTSavePrimed;
import com.xeraster.supertnt.renders.RenderTNTSingularityPrimed;
import com.xeraster.supertnt.renders.RenderTNTSnowPrimed;
import com.xeraster.supertnt.renders.RenderTNTSpongePrimed;
import com.xeraster.supertnt.renders.RenderTNTSuperClusterPrimed;
import com.xeraster.supertnt.renders.RenderTNTSuperPrimed;
import com.xeraster.supertnt.renders.RenderTNTTeleportPrimed;
import com.xeraster.supertnt.renders.RenderTNTThunderPrimed;
import com.xeraster.supertnt.renders.RenderTNTTimePrimed;
import com.xeraster.supertnt.renders.RenderTNTTinyIslandPrimed;
import com.xeraster.supertnt.renders.RenderTNTTreePrimed;
import com.xeraster.supertnt.renders.RenderTNTTrumpPrimed;
import com.xeraster.supertnt.renders.RenderTNTWarpPrimed;
import com.xeraster.supertnt.renders.RenderTNTWavePrimed;
import com.xeraster.supertnt.renders.RenderTNTWeatherPrimed;
import com.xeraster.supertnt.renders.RenderTNTWeedPrimed;
import com.xeraster.supertnt.renders.RenderTNTWtfPrimed;
import java.util.HashSet;
import java.util.Set;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent.Register;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;
import org.apache.logging.log4j.Logger;

@Mod(
    modid = "supertnt",
    name = "Super TNT Mod",
    version = "1.0.1",
    acceptedMinecraftVersions = "[1.12.2]"
)
public class SuperTNTMod {

    public static final String MODID = "supertnt";
    public static final String NAME = "Super TNT Mod";
    public static final String VERSION = "1.0.1";
    public static final ModFluid LIQUID_POOP = (ModFluid) (new ModFluid("liquidpoop", new ResourceLocation("supertnt", "liquidpoop_still"), new ResourceLocation("supertnt", "liquidpoop_flow"))).setMaterial(ModMaterials.POOPD).setDensity(1000).setGaseous(false).setLuminosity(0).setViscosity(1000).setTemperature(295);
    public static BlockFluidPoop BlockLiquidPoop = null;
    public static final BlockGlassDiamond DIAMOND_GLASS = new BlockGlassDiamond(Material.GLASS, true);
    public static final BlockTestBlock WHATEVER_TEST = new BlockTestBlock("testblock", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockCheeseBlock CHEESE_BLOCK = new BlockCheeseBlock("cheeseblock", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockCheeseLeaves CHEESE_LEAVES = new BlockCheeseLeaves("cheeseleaves", Material.LEAVES, CreativeTabs.BUILDING_BLOCKS, 0.2F, 0.2F, "axe", 0);
    public static final BlockCheeseGrass CHEESE_GRASS = new BlockCheeseGrass("cheesegrass");
    public static final BlockCheeseBush CHEESE_BUSH = new BlockCheeseBush("cheesebush");
    public static final BlockEyeLol EYETEST_BLOCK = new BlockEyeLol("eyeblocklol", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockMouthLol MOUTHTEST_BLOCK = new BlockMouthLol("mouthblocklol", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockSolidPoop POOP_BLOCK = new BlockSolidPoop("solidpoop", Material.GROUND, CreativeTabs.BUILDING_BLOCKS, 0.5F, 2.5F, "pickaxe", 0);
    public static final BlockPoopLeaves POOP_LEAVES = new BlockPoopLeaves("poopleaves", Material.LEAVES, CreativeTabs.BUILDING_BLOCKS, 0.2F, 0.2F, "axe", 0);
    public static final BlockGayLeaves LESBIAN_LEAVES = new BlockGayLeaves("lesbianleaves", Material.LEAVES, CreativeTabs.BUILDING_BLOCKS, 0.2F, 0.2F, "axe", 0);
    public static final BlockCrapGrass CRAP_GRASS = new BlockCrapGrass("crapgrass");
    public static final BlockPoopPlant POOP_PLANT = new BlockPoopPlant("poopplant");
    public static final BlockGayPlant GAY_BUSH = new BlockGayPlant("gaybush");
    public static final BlockGayPlant TRANS_GRASS = new BlockGayPlant("transgrass");
    public static final BlockGayPlant PANSEXUAL_FLOWER = new BlockGayPlant("pansexualflower");
    public static final BlockNoAnswer NO_ANSWER = new BlockNoAnswer("noanswer", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockYesAnswer YES_ANSWER = new BlockYesAnswer("yesanswer", Material.ROCK, CreativeTabs.BUILDING_BLOCKS, 5.0F, 15.0F, "pickaxe", 0);
    public static final BlockTNTLarge LARGE_TNT = new BlockTNTLarge("largetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTMassive MASSIVE_TNT = new BlockTNTMassive("massivetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSuper SUPER_TNT = new BlockTNTSuper("supertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTDoom DOOM_TNT = new BlockTNTDoom("doomtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTEnd END_TNT = new BlockTNTEnd("endtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTWtf WTF_TNT = new BlockTNTWtf("wtftnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSingularity SINGULARITY_TNT = new BlockTNTSingularity("singularitytnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTPleaseNo PLEASENO_TNT = new BlockTNTPleaseNo("pleasenotnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTBiome BIOME_TNT = new BlockTNTBiome("biometnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCluster CLUSTER_TNT = new BlockTNTCluster("clustertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSuperCluster SUPERCLUSTER_TNT = new BlockTNTSuperCluster("superclustertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTHell HELL_TNT = new BlockTNTHell("helltnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTFire FIRE_TNT = new BlockTNTFire("firetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSnow SNOW_TNT = new BlockTNTSnow("snowtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTOcean OCEAN_TNT = new BlockTNTOcean("oceantnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSponge SPONGE_TNT = new BlockTNTSponge("spongetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTLavaOcean LAVAOCEAN_TNT = new BlockTNTLavaOcean("lavaoceantnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTDiamond DIAMOND_TNT = new BlockTNTDiamond("diamondtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTHouse HOUSE_TNT = new BlockTNTHouse("housetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTBunker BUNKER_TNT = new BlockTNTBunker("bunkertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTMob MOB_TNT = new BlockTNTMob("mobtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTMob2 MOB2_TNT = new BlockTNTMob2("mob2tnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTMob3 MOB3_TNT = new BlockTNTMob3("mob3tnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTNoMob NOMOB_TNT = new BlockTNTNoMob("nomobtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTArrow ARROW_TNT = new BlockTNTArrow("arrowtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTTree TREE_TNT = new BlockTNTTree("treestnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTForest FOREST_TNT = new BlockTNTForest("foresttnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTTinyIsland TINYISLAND_TNT = new BlockTNTTinyIsland("tinyislandtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTIsland ISLAND_TNT = new BlockTNTIsland("islandtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTNostalgia NOSTALGIA_TNT = new BlockTNTNostalgia("nostalgiatnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTEverything EVERYTHING_TNT = new BlockTNTEverything("everythingtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTLGBT LGBT_TNT = new BlockTNTLGBT("lgbttnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTTrump TRUMP_TNT = new BlockTNTTrump("trumptnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTKimJong KIMJONG_TNT = new BlockTNTKimJong("kimjongtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTChristmas CHRISTMAS_TNT = new BlockTNTChristmas("isitchristmastnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCrap CRAP_TNT = new BlockTNTCrap("craptnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCrap2 CRAP2_TNT = new BlockTNTCrap2("crap2tnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCheese CHEESE_TNT = new BlockTNTCheese("cheesetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTFlat FLAT_TNT = new BlockTNTFlat("flattnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTMine MINE_TNT = new BlockTNTMine("minetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTRake RAKE_TNT = new BlockTNTRake("raketnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTTime TIME_TNT = new BlockTNTTime("timetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTWeather WEATHER_TNT = new BlockTNTWeather("weathertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTThunder THUNDER_TNT = new BlockTNTThunder("thundertnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCrack CRACK_TNT = new BlockTNTCrack("cracktnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTWeed WEED_TNT = new BlockTNTWeed("weedtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTFact FACT_TNT = new BlockTNTFact("facttnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTCave CAVE_TNT = new BlockTNTCave("cavetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTSave SAVE_TNT = new BlockTNTSave("savetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTWave WAVE_TNT = new BlockTNTWave("wavetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTAirborne AIRBORNE_TNT = new BlockTNTAirborne("airbornetnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTJail JAIL_TNT = new BlockTNTJail("jailtnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTTeleport TELEPORT_TNT = new BlockTNTTeleport("teleporttnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTWarp WARP_TNT = new BlockTNTWarp("warptnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTDiamondNuke DIAMONDNUKE_TNT = new BlockTNTDiamondNuke("diamondnuketnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final BlockTNTLava LAVA_TNT = new BlockTNTLava("lavatnt", Material.TNT, CreativeTabs.REDSTONE, 2.0F, 1.0F, "pickaxe", 0);
    public static final EntityEntry LARGE_TNT_ENTITY = new EntityEntry(EntityTNTLargePrimed.class, "supertnt:large_tnt_primed");
    public static final EntityEntry MASSIVE_TNT_ENTITY = new EntityEntry(EntityTNTMassivePrimed.class, "supertnt:massive_tnt_primed");
    public static final EntityEntry SUPER_TNT_ENTITY = new EntityEntry(EntityTNTSuperPrimed.class, "supertnt:super_tnt_primed");
    public static final EntityEntry DOOM_TNT_ENTITY = new EntityEntry(EntityTNTDoomPrimed.class, "supertnt:doom_tnt_primed");
    public static final EntityEntry END_TNT_ENTITY = new EntityEntry(EntityTNTEndPrimed.class, "supertnt:end_tnt_primed");
    public static final EntityEntry WAVE_TNT_ENTITY = new EntityEntry(EntityTNTWavePrimed.class, "supertnt:wave_tnt_primed");
    public static final EntityEntry OCEAN_TNT_ENTITY = new EntityEntry(EntityTNTOceanPrimed.class, "supertnt:ocean_tnt_primed");
    public static final EntityEntry SPONGE_TNT_ENTITY = new EntityEntry(EntityTNTSpongePrimed.class, "supertnt:sponge_tnt_primed");
    public static final EntityEntry FIRE_TNT_ENTITY = new EntityEntry(EntityTNTFirePrimed.class, "supertnt:fire_tnt_primed");
    public static final EntityEntry BIOME_TNT_ENTITY = new EntityEntry(EntityTNTBiomePrimed.class, "supertnt:biome_tnt_primed");
    public static final EntityEntry CHRISTMAS_TNT_ENTITY = new EntityEntry(EntityTNTChristmasPrimed.class, "supertnt:christmas_tnt_primed");
    public static final EntityEntry CRAP_TNT_ENTITY = new EntityEntry(EntityTNTCrapPrimed.class, "supertnt:crap_tnt_primed");
    public static final EntityEntry CRAP2_TNT_ENTITY = new EntityEntry(EntityTNTCrap2Primed.class, "supertnt:crap2_tnt_primed");
    public static final EntityEntry CAVE_TNT_ENTITY = new EntityEntry(EntityTNTCavePrimed.class, "supertnt:cave_tnt_primed");
    public static final EntityEntry DIAMONDNUKE_TNT_ENTITY = new EntityEntry(EntityTNTDiamondNukePrimed.class, "supertnt:diamondnuke_tnt_primed");
    public static final EntityEntry DIAMOND_TNT_ENTITY = new EntityEntry(EntityTNTDiamondPrimed.class, "supertnt:diamond_tnt_primed");
    public static final EntityEntry MOB_TNT_ENTITY = new EntityEntry(EntityTNTMobPrimed.class, "supertnt:mob_tnt_primed");
    public static final EntityEntry MOB2_TNT_ENTITY = new EntityEntry(EntityTNTMob2Primed.class, "supertnt:mob2_tnt_primed");
    public static final EntityEntry MOB3_TNT_ENTITY = new EntityEntry(EntityTNTMob3Primed.class, "supertnt:mob3_tnt_primed");
    public static final EntityEntry NOMOB_TNT_ENTITY = new EntityEntry(EntityTNTNoMobPrimed.class, "supertnt:nomob_tnt_primed");
    public static final EntityEntry SNOW_TNT_ENTITY = new EntityEntry(EntityTNTSnowPrimed.class, "supertnt:snow_tnt_primed");
    public static final EntityEntry EVERYTHING_TNT_ENTITY = new EntityEntry(EntityTNTEverythingPrimed.class, "supertnt:everything_tnt_primed");
    public static final EntityEntry FLAT_TNT_ENTITY = new EntityEntry(EntityTNTFlatPrimed.class, "supertnt:flat_tnt_primed");
    public static final EntityEntry HOUSE_TNT_ENTITY = new EntityEntry(EntityTNTHousePrimed.class, "supertnt:house_tnt_primed");
    public static final EntityEntry MINE_TNT_ENTITY = new EntityEntry(EntityTNTMinePrimed.class, "supertnt:mine_tnt_primed");
    public static final EntityEntry NOSTALGIA_TNT_ENTITY = new EntityEntry(EntityTNTNostalgiaPrimed.class, "supertnt:nostalgia_tnt_primed");
    public static final EntityEntry SAVE_TNT_ENTITY = new EntityEntry(EntityTNTSavePrimed.class, "supertnt:save_tnt_primed");
    public static final EntityEntry CLUSTER_TNT_ENTITY = new EntityEntry(EntityTNTClusterPrimed.class, "supertnt:cluster_tnt_primed");
    public static final EntityEntry SUPERCLUSTER_TNT_ENTITY = new EntityEntry(EntityTNTSuperClusterPrimed.class, "supertnt:supercluster_tnt_primed");
    public static final EntityEntry HELL_TNT_ENTITY = new EntityEntry(EntityTNTHellPrimed.class, "supertnt:hell_tnt_primed");
    public static final EntityEntry THUNDER_TNT_ENTITY = new EntityEntry(EntityTNTThunderPrimed.class, "supertnt:thunder_tnt_primed");
    public static final EntityEntry TRUMP_TNT_ENTITY = new EntityEntry(EntityTNTTrumpPrimed.class, "supertnt:trump_tnt_primed");
    public static final EntityEntry KIMJONG_TNT_ENTITY = new EntityEntry(EntityTNTKimJongPrimed.class, "supertnt:kimjong_tnt_primed");
    public static final EntityEntry TREE_TNT_ENTITY = new EntityEntry(EntityTNTTreePrimed.class, "supertnt:tree_tnt_primed");
    public static final EntityEntry FOREST_TNT_ENTITY = new EntityEntry(EntityTNTForestPrimed.class, "supertnt:forest_tnt_primed");
    public static final EntityEntry LAVA_TNT_ENTITY = new EntityEntry(EntityTNTLavaPrimed.class, "supertnt:lava_tnt_primed");
    public static final EntityEntry CRACK_TNT_ENTITY = new EntityEntry(EntityTNTCrackPrimed.class, "supertnt:crack_tnt_primed");
    public static final EntityEntry WEED_TNT_ENTITY = new EntityEntry(EntityTNTWeedPrimed.class, "supertnt:weed_tnt_primed");
    public static final EntityEntry WTF_TNT_ENTITY = new EntityEntry(EntityTNTWtfPrimed.class, "supertnt:wtf_tnt_primed");
    public static final EntityEntry BUNKER_TNT_ENTITY = new EntityEntry(EntityTNTBunkerPrimed.class, "supertnt:bunker_tnt_primed");
    public static final EntityEntry ISLAND_TNT_ENTITY = new EntityEntry(EntityTNTIslandPrimed.class, "supertnt:island_tnt_primed");
    public static final EntityEntry SINGULARITY_TNT_ENTITY = new EntityEntry(EntityTNTSingularityPrimed.class, "supertnt:singularity_tnt_primed");
    public static final EntityEntry PLEASENO_TNT_ENTITY = new EntityEntry(EntityTNTPleaseNoPrimed.class, "supertnt:pleaseno_tnt_primed");
    public static final EntityEntry WEATHER_TNT_ENTITY = new EntityEntry(EntityTNTWeatherPrimed.class, "supertnt:weather_tnt_primed");
    public static final EntityEntry TIME_TNT_ENTITY = new EntityEntry(EntityTNTTimePrimed.class, "supertnt:time_tnt_primed");
    public static final EntityEntry RAKE_TNT_ENTITY = new EntityEntry(EntityTNTRakePrimed.class, "supertnt:rake_tnt_primed");
    public static final EntityEntry LGBT_TNT_ENTITY = new EntityEntry(EntityTNTLGBTPrimed.class, "supertnt:lgbt_tnt_primed");
    public static final EntityEntry CHEESE_TNT_ENTITY = new EntityEntry(EntityTNTCheesePrimed.class, "supertnt:cheese_tnt_primed");
    public static final EntityEntry LAVAOCEAN_TNT_ENTITY = new EntityEntry(EntityTNTLavaOceanPrimed.class, "supertnt:lavaocean_tnt_primed");
    public static final EntityEntry TINYISLAND_TNT_ENTITY = new EntityEntry(EntityTNTTinyIslandPrimed.class, "supertnt:tinyisland_tnt_primed");
    public static final EntityEntry FACT_TNT_ENTITY = new EntityEntry(EntityTNTFactPrimed.class, "supertnt:fact_tnt_primed");
    public static final EntityEntry ARROW_TNT_ENTITY = new EntityEntry(EntityTNTArrowPrimed.class, "supertnt:arrow_tnt_primed");
    public static final EntityEntry AIRBORNE_TNT_ENTITY = new EntityEntry(EntityTNTAirbornePrimed.class, "supertnt:airborne_tnt_primed");
    public static final EntityEntry JAIL_TNT_ENTITY = new EntityEntry(EntityTNTJailPrimed.class, "supertnt:jail_tnt_primed");
    public static final EntityEntry TELEPORT_TNT_ENTITY = new EntityEntry(EntityTNTTeleportPrimed.class, "supertnt:teleport_tnt_primed");
    public static final EntityEntry WARP_TNT_ENTITY = new EntityEntry(EntityTNTWarpPrimed.class, "supertnt:warp_tnt_primed");
    private static Logger logger;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        System.out.println("Pre initialization event executed");
        SuperTNTMod.logger = event.getModLog();
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.LARGE_TNT_ENTITY.getEntityClass(), new RenderTNTLargePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.MASSIVE_TNT_ENTITY.getEntityClass(), new RenderTNTMassivePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SUPER_TNT_ENTITY.getEntityClass(), new RenderTNTSuperPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.DOOM_TNT_ENTITY.getEntityClass(), new RenderTNTDoomPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.END_TNT_ENTITY.getEntityClass(), new RenderTNTEndPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.WAVE_TNT_ENTITY.getEntityClass(), new RenderTNTWavePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.OCEAN_TNT_ENTITY.getEntityClass(), new RenderTNTOceanPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SPONGE_TNT_ENTITY.getEntityClass(), new RenderTNTSpongePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.FIRE_TNT_ENTITY.getEntityClass(), new RenderTNTFirePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.BIOME_TNT_ENTITY.getEntityClass(), new RenderTNTBiomePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CHRISTMAS_TNT_ENTITY.getEntityClass(), new RenderTNTChristmasPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CRAP_TNT_ENTITY.getEntityClass(), new RenderTNTCrapPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CAVE_TNT_ENTITY.getEntityClass(), new RenderTNTCavePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.DIAMONDNUKE_TNT_ENTITY.getEntityClass(), new RenderTNTDiamondNukePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.DIAMOND_TNT_ENTITY.getEntityClass(), new RenderTNTDiamondPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.MOB_TNT_ENTITY.getEntityClass(), new RenderTNTMobPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.MOB2_TNT_ENTITY.getEntityClass(), new RenderTNTMob2Primed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.MOB3_TNT_ENTITY.getEntityClass(), new RenderTNTMob3Primed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.NOMOB_TNT_ENTITY.getEntityClass(), new RenderTNTNoMobPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SNOW_TNT_ENTITY.getEntityClass(), new RenderTNTSnowPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.EVERYTHING_TNT_ENTITY.getEntityClass(), new RenderTNTEverythingPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.FLAT_TNT_ENTITY.getEntityClass(), new RenderTNTFlatPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.HOUSE_TNT_ENTITY.getEntityClass(), new RenderTNTHousePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.MINE_TNT_ENTITY.getEntityClass(), new RenderTNTMinePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.NOSTALGIA_TNT_ENTITY.getEntityClass(), new RenderTNTNostalgiaPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SAVE_TNT_ENTITY.getEntityClass(), new RenderTNTSavePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CRAP2_TNT_ENTITY.getEntityClass(), new RenderTNTCrap2Primed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CLUSTER_TNT_ENTITY.getEntityClass(), new RenderTNTClusterPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SUPERCLUSTER_TNT_ENTITY.getEntityClass(), new RenderTNTSuperClusterPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.HELL_TNT_ENTITY.getEntityClass(), new RenderTNTHellPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.THUNDER_TNT_ENTITY.getEntityClass(), new RenderTNTThunderPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.TRUMP_TNT_ENTITY.getEntityClass(), new RenderTNTTrumpPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.KIMJONG_TNT_ENTITY.getEntityClass(), new RenderTNTKimJongPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.TREE_TNT_ENTITY.getEntityClass(), new RenderTNTTreePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.FOREST_TNT_ENTITY.getEntityClass(), new RenderTNTForestPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.LAVA_TNT_ENTITY.getEntityClass(), new RenderTNTLavaPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CRACK_TNT_ENTITY.getEntityClass(), new RenderTNTCrackPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.WEED_TNT_ENTITY.getEntityClass(), new RenderTNTWeedPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.WTF_TNT_ENTITY.getEntityClass(), new RenderTNTWtfPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.BUNKER_TNT_ENTITY.getEntityClass(), new RenderTNTBunkerPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.ISLAND_TNT_ENTITY.getEntityClass(), new RenderTNTIslandPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.SINGULARITY_TNT_ENTITY.getEntityClass(), new RenderTNTSingularityPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.PLEASENO_TNT_ENTITY.getEntityClass(), new RenderTNTPleaseNoPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.WEATHER_TNT_ENTITY.getEntityClass(), new RenderTNTWeatherPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.TIME_TNT_ENTITY.getEntityClass(), new RenderTNTTimePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.RAKE_TNT_ENTITY.getEntityClass(), new RenderTNTRakePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.LGBT_TNT_ENTITY.getEntityClass(), new RenderTNTLGBTPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.CHEESE_TNT_ENTITY.getEntityClass(), new RenderTNTCheesePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.LAVAOCEAN_TNT_ENTITY.getEntityClass(), new RenderTNTLavaOceanPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.TINYISLAND_TNT_ENTITY.getEntityClass(), new RenderTNTTinyIslandPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.FACT_TNT_ENTITY.getEntityClass(), new RenderTNTFactPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.ARROW_TNT_ENTITY.getEntityClass(), new RenderTNTArrowPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.AIRBORNE_TNT_ENTITY.getEntityClass(), new RenderTNTAirbornePrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.JAIL_TNT_ENTITY.getEntityClass(), new RenderTNTJailPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.TELEPORT_TNT_ENTITY.getEntityClass(), new RenderTNTTeleportPrimed(Minecraft.getMinecraft().getRenderManager()));
        RenderingRegistry.registerEntityRenderingHandler(SuperTNTMod.WARP_TNT_ENTITY.getEntityClass(), new RenderTNTWarpPrimed(Minecraft.getMinecraft().getRenderManager()));
        System.out.println("About to run SoundHandler.init()");
    }

    @EventBusSubscriber(
        modid = "supertnt"
    )
    public static class RegistrationHandler {

        public static final Set ITEM_BLOCKS = new HashSet();

        @SubscribeEvent
        public static void registerBlocks(Register<Block> event) {
            IForgeRegistry<Block> registry = event.getRegistry();

            FluidRegistry.registerFluid(SuperTNTMod.LIQUID_POOP);
            SuperTNTMod.BlockLiquidPoop = new BlockFluidPoop();
            Block[] blocks = new Block[] { SuperTNTMod.BlockLiquidPoop, SuperTNTMod.DIAMOND_GLASS, SuperTNTMod.WHATEVER_TEST, SuperTNTMod.CHEESE_BLOCK, SuperTNTMod.CHEESE_LEAVES, SuperTNTMod.CHEESE_GRASS, SuperTNTMod.CHEESE_BUSH, SuperTNTMod.EYETEST_BLOCK, SuperTNTMod.MOUTHTEST_BLOCK, SuperTNTMod.POOP_BLOCK, SuperTNTMod.POOP_LEAVES, SuperTNTMod.LESBIAN_LEAVES, SuperTNTMod.CRAP_GRASS, SuperTNTMod.POOP_PLANT, SuperTNTMod.GAY_BUSH, SuperTNTMod.TRANS_GRASS, SuperTNTMod.PANSEXUAL_FLOWER, SuperTNTMod.NO_ANSWER, SuperTNTMod.YES_ANSWER, SuperTNTMod.LARGE_TNT, SuperTNTMod.MASSIVE_TNT, SuperTNTMod.SUPER_TNT, SuperTNTMod.DOOM_TNT, SuperTNTMod.END_TNT, SuperTNTMod.WTF_TNT, SuperTNTMod.SINGULARITY_TNT, SuperTNTMod.PLEASENO_TNT, SuperTNTMod.BIOME_TNT, SuperTNTMod.CLUSTER_TNT, SuperTNTMod.SUPERCLUSTER_TNT, SuperTNTMod.HELL_TNT, SuperTNTMod.FIRE_TNT, SuperTNTMod.SNOW_TNT, SuperTNTMod.OCEAN_TNT, SuperTNTMod.SPONGE_TNT, SuperTNTMod.LAVAOCEAN_TNT, SuperTNTMod.DIAMOND_TNT, SuperTNTMod.HOUSE_TNT, SuperTNTMod.BUNKER_TNT, SuperTNTMod.MOB_TNT, SuperTNTMod.MOB2_TNT, SuperTNTMod.MOB3_TNT, SuperTNTMod.NOMOB_TNT, SuperTNTMod.ARROW_TNT, SuperTNTMod.TREE_TNT, SuperTNTMod.FOREST_TNT, SuperTNTMod.TINYISLAND_TNT, SuperTNTMod.ISLAND_TNT, SuperTNTMod.NOSTALGIA_TNT, SuperTNTMod.EVERYTHING_TNT, SuperTNTMod.LGBT_TNT, SuperTNTMod.TRUMP_TNT, SuperTNTMod.KIMJONG_TNT, SuperTNTMod.CHRISTMAS_TNT, SuperTNTMod.CRAP_TNT, SuperTNTMod.CRAP2_TNT, SuperTNTMod.CHEESE_TNT, SuperTNTMod.FLAT_TNT, SuperTNTMod.MINE_TNT, SuperTNTMod.RAKE_TNT, SuperTNTMod.TIME_TNT, SuperTNTMod.WEATHER_TNT, SuperTNTMod.THUNDER_TNT, SuperTNTMod.CRACK_TNT, SuperTNTMod.WEED_TNT, SuperTNTMod.FACT_TNT, SuperTNTMod.CAVE_TNT, SuperTNTMod.SAVE_TNT, SuperTNTMod.WAVE_TNT, SuperTNTMod.AIRBORNE_TNT, SuperTNTMod.JAIL_TNT, SuperTNTMod.TELEPORT_TNT, SuperTNTMod.WARP_TNT, SuperTNTMod.DIAMONDNUKE_TNT, SuperTNTMod.LAVA_TNT};

            registry.registerAll(blocks);
            System.out.println("register all function executed");
        }

        @SubscribeEvent
        public static void registerStuff(Register<EntityEntry> event) {
            System.out.println("registerStuff got executed");
            SuperTNTMod.LARGE_TNT_ENTITY.setRegistryName("supertnt", "large_tnt_1");
            SuperTNTMod.MASSIVE_TNT_ENTITY.setRegistryName("supertnt", "massive_tnt_1");
            SuperTNTMod.SUPER_TNT_ENTITY.setRegistryName("supertnt", "super_tnt_1");
            SuperTNTMod.DOOM_TNT_ENTITY.setRegistryName("supertnt", "doom_tnt_1");
            SuperTNTMod.END_TNT_ENTITY.setRegistryName("supertnt", "end_tnt_1");
            SuperTNTMod.WAVE_TNT_ENTITY.setRegistryName("supertnt", "wave_tnt_1");
            SuperTNTMod.OCEAN_TNT_ENTITY.setRegistryName("supertnt", "ocean_tnt_1");
            SuperTNTMod.SPONGE_TNT_ENTITY.setRegistryName("supertnt", "sponge_tnt_1");
            SuperTNTMod.FIRE_TNT_ENTITY.setRegistryName("supertnt", "fire_tnt_1");
            SuperTNTMod.BIOME_TNT_ENTITY.setRegistryName("supertnt", "biome_tnt_1");
            SuperTNTMod.CHRISTMAS_TNT_ENTITY.setRegistryName("supertnt", "christmas_tnt_1");
            SuperTNTMod.CRAP_TNT_ENTITY.setRegistryName("supertnt", "crap_tnt_1");
            SuperTNTMod.CRAP2_TNT_ENTITY.setRegistryName("supertnt", "crap2_tnt_1");
            SuperTNTMod.CAVE_TNT_ENTITY.setRegistryName("supertnt", "cave_tnt_1");
            SuperTNTMod.DIAMONDNUKE_TNT_ENTITY.setRegistryName("supertnt", "diamondnuke_tnt_1");
            SuperTNTMod.DIAMOND_TNT_ENTITY.setRegistryName("supertnt", "diamond_tnt_1");
            SuperTNTMod.MOB_TNT_ENTITY.setRegistryName("supertnt", "mob_tnt_1");
            SuperTNTMod.MOB2_TNT_ENTITY.setRegistryName("supertnt", "mob2_tnt_1");
            SuperTNTMod.MOB3_TNT_ENTITY.setRegistryName("supertnt", "mob3_tnt_1");
            SuperTNTMod.NOMOB_TNT_ENTITY.setRegistryName("supertnt", "nomob_tnt_1");
            SuperTNTMod.SNOW_TNT_ENTITY.setRegistryName("supertnt", "snow_tnt_1");
            SuperTNTMod.EVERYTHING_TNT_ENTITY.setRegistryName("supertnt", "everything_tnt_1");
            SuperTNTMod.FLAT_TNT_ENTITY.setRegistryName("supertnt", "flat_tnt_1");
            SuperTNTMod.HOUSE_TNT_ENTITY.setRegistryName("supertnt", "house_tnt_1");
            SuperTNTMod.MINE_TNT_ENTITY.setRegistryName("supertnt", "mine_tnt_1");
            SuperTNTMod.NOSTALGIA_TNT_ENTITY.setRegistryName("supertnt", "nostalgia_tnt_1");
            SuperTNTMod.SAVE_TNT_ENTITY.setRegistryName("supertnt", "save_tnt_1");
            SuperTNTMod.CLUSTER_TNT_ENTITY.setRegistryName("supertnt", "cluster_tnt_1");
            SuperTNTMod.SUPERCLUSTER_TNT_ENTITY.setRegistryName("supertnt", "supercluster_tnt_1");
            SuperTNTMod.HELL_TNT_ENTITY.setRegistryName("supertnt", "hell_tnt_1");
            SuperTNTMod.THUNDER_TNT_ENTITY.setRegistryName("supertnt", "thunder_tnt_1");
            SuperTNTMod.TRUMP_TNT_ENTITY.setRegistryName("supertnt", "trump_tnt_1");
            SuperTNTMod.KIMJONG_TNT_ENTITY.setRegistryName("supertnt", "kimjong_tnt_1");
            SuperTNTMod.TREE_TNT_ENTITY.setRegistryName("supertnt", "tree_tnt_1");
            SuperTNTMod.FOREST_TNT_ENTITY.setRegistryName("supertnt", "forest_tnt_1");
            SuperTNTMod.LAVA_TNT_ENTITY.setRegistryName("supertnt", "lava_tnt_1");
            SuperTNTMod.CRACK_TNT_ENTITY.setRegistryName("supertnt", "crack_tnt_1");
            SuperTNTMod.WEED_TNT_ENTITY.setRegistryName("supertnt", "weed_tnt_1");
            SuperTNTMod.WTF_TNT_ENTITY.setRegistryName("supertnt", "wtf_tnt_1");
            SuperTNTMod.BUNKER_TNT_ENTITY.setRegistryName("supertnt", "bunker_tnt_1");
            SuperTNTMod.ISLAND_TNT_ENTITY.setRegistryName("supertnt", "island_tnt_1");
            SuperTNTMod.SINGULARITY_TNT_ENTITY.setRegistryName("supertnt", "singularity_tnt_1");
            SuperTNTMod.PLEASENO_TNT_ENTITY.setRegistryName("supertnt", "pleaseno_tnt_1");
            SuperTNTMod.WEATHER_TNT_ENTITY.setRegistryName("supertnt", "weather_tnt_1");
            SuperTNTMod.TIME_TNT_ENTITY.setRegistryName("supertnt", "time_tnt_1");
            SuperTNTMod.RAKE_TNT_ENTITY.setRegistryName("supertnt", "rake_tnt_1");
            SuperTNTMod.LGBT_TNT_ENTITY.setRegistryName("supertnt", "lgbt_tnt_1");
            SuperTNTMod.CHEESE_TNT_ENTITY.setRegistryName("supertnt", "cheese_tnt_1");
            SuperTNTMod.LAVAOCEAN_TNT_ENTITY.setRegistryName("supertnt", "lavaocean_tnt_1");
            SuperTNTMod.TINYISLAND_TNT_ENTITY.setRegistryName("supertnt", "tinyisland_tnt_1");
            SuperTNTMod.FACT_TNT_ENTITY.setRegistryName("supertnt", "fact_tnt_1");
            SuperTNTMod.ARROW_TNT_ENTITY.setRegistryName("supertnt", "arrow_tnt_1");
            SuperTNTMod.AIRBORNE_TNT_ENTITY.setRegistryName("supertnt", "airborne_tnt_1");
            SuperTNTMod.JAIL_TNT_ENTITY.setRegistryName("supertnt", "jail_tnt_1");
            SuperTNTMod.TELEPORT_TNT_ENTITY.setRegistryName("supertnt", "teleport_tnt_1");
            SuperTNTMod.WARP_TNT_ENTITY.setRegistryName("supertnt", "warp_tnt_1");
            event.getRegistry().register(SuperTNTMod.LARGE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.MASSIVE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SUPER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.DOOM_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.END_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.WAVE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.OCEAN_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SPONGE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.FIRE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.BIOME_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CHRISTMAS_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CRAP_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CRAP2_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CAVE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.DIAMONDNUKE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.DIAMOND_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.MOB_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.MOB2_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.MOB3_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.NOMOB_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SNOW_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.EVERYTHING_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.FLAT_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.HOUSE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.MINE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.NOSTALGIA_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SAVE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CLUSTER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SUPERCLUSTER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.HELL_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.THUNDER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.TRUMP_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.KIMJONG_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.TREE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.FOREST_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.LAVA_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CRACK_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.WEED_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.WTF_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.BUNKER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.ISLAND_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.SINGULARITY_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.PLEASENO_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.WEATHER_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.TIME_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.RAKE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.LGBT_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.CHEESE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.LAVAOCEAN_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.TINYISLAND_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.FACT_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.ARROW_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.AIRBORNE_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.JAIL_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.TELEPORT_TNT_ENTITY);
            event.getRegistry().register(SuperTNTMod.WARP_TNT_ENTITY);
            EntityRegistry.registerModEntity(SuperTNTMod.LARGE_TNT_ENTITY.getRegistryName(), SuperTNTMod.LARGE_TNT_ENTITY.getEntityClass(), SuperTNTMod.LARGE_TNT_ENTITY.getName(), 0, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.MASSIVE_TNT_ENTITY.getRegistryName(), SuperTNTMod.MASSIVE_TNT_ENTITY.getEntityClass(), SuperTNTMod.MASSIVE_TNT_ENTITY.getName(), 1, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SUPER_TNT_ENTITY.getRegistryName(), SuperTNTMod.SUPER_TNT_ENTITY.getEntityClass(), SuperTNTMod.SUPER_TNT_ENTITY.getName(), 2, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.DOOM_TNT_ENTITY.getRegistryName(), SuperTNTMod.DOOM_TNT_ENTITY.getEntityClass(), SuperTNTMod.DOOM_TNT_ENTITY.getName(), 3, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.END_TNT_ENTITY.getRegistryName(), SuperTNTMod.END_TNT_ENTITY.getEntityClass(), SuperTNTMod.END_TNT_ENTITY.getName(), 4, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.WAVE_TNT_ENTITY.getRegistryName(), SuperTNTMod.WAVE_TNT_ENTITY.getEntityClass(), SuperTNTMod.WAVE_TNT_ENTITY.getName(), 5, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.OCEAN_TNT_ENTITY.getRegistryName(), SuperTNTMod.OCEAN_TNT_ENTITY.getEntityClass(), SuperTNTMod.OCEAN_TNT_ENTITY.getName(), 6, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SPONGE_TNT_ENTITY.getRegistryName(), SuperTNTMod.SPONGE_TNT_ENTITY.getEntityClass(), SuperTNTMod.SPONGE_TNT_ENTITY.getName(), 7, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.FIRE_TNT_ENTITY.getRegistryName(), SuperTNTMod.FIRE_TNT_ENTITY.getEntityClass(), SuperTNTMod.FIRE_TNT_ENTITY.getName(), 8, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.BIOME_TNT_ENTITY.getRegistryName(), SuperTNTMod.BIOME_TNT_ENTITY.getEntityClass(), SuperTNTMod.BIOME_TNT_ENTITY.getName(), 9, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CHRISTMAS_TNT_ENTITY.getRegistryName(), SuperTNTMod.CHRISTMAS_TNT_ENTITY.getEntityClass(), SuperTNTMod.CHRISTMAS_TNT_ENTITY.getName(), 10, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CRAP_TNT_ENTITY.getRegistryName(), SuperTNTMod.CRAP_TNT_ENTITY.getEntityClass(), SuperTNTMod.CRAP_TNT_ENTITY.getName(), 11, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CAVE_TNT_ENTITY.getRegistryName(), SuperTNTMod.CAVE_TNT_ENTITY.getEntityClass(), SuperTNTMod.CAVE_TNT_ENTITY.getName(), 12, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.DIAMONDNUKE_TNT_ENTITY.getRegistryName(), SuperTNTMod.DIAMONDNUKE_TNT_ENTITY.getEntityClass(), SuperTNTMod.DIAMONDNUKE_TNT_ENTITY.getName(), 13, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.DIAMOND_TNT_ENTITY.getRegistryName(), SuperTNTMod.DIAMOND_TNT_ENTITY.getEntityClass(), SuperTNTMod.DIAMOND_TNT_ENTITY.getName(), 14, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.MOB_TNT_ENTITY.getRegistryName(), SuperTNTMod.MOB_TNT_ENTITY.getEntityClass(), SuperTNTMod.MOB_TNT_ENTITY.getName(), 15, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.MOB2_TNT_ENTITY.getRegistryName(), SuperTNTMod.MOB2_TNT_ENTITY.getEntityClass(), SuperTNTMod.MOB2_TNT_ENTITY.getName(), 16, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.MOB3_TNT_ENTITY.getRegistryName(), SuperTNTMod.MOB3_TNT_ENTITY.getEntityClass(), SuperTNTMod.MOB3_TNT_ENTITY.getName(), 17, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.NOMOB_TNT_ENTITY.getRegistryName(), SuperTNTMod.NOMOB_TNT_ENTITY.getEntityClass(), SuperTNTMod.NOMOB_TNT_ENTITY.getName(), 18, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SNOW_TNT_ENTITY.getRegistryName(), SuperTNTMod.SNOW_TNT_ENTITY.getEntityClass(), SuperTNTMod.SNOW_TNT_ENTITY.getName(), 19, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.EVERYTHING_TNT_ENTITY.getRegistryName(), SuperTNTMod.EVERYTHING_TNT_ENTITY.getEntityClass(), SuperTNTMod.EVERYTHING_TNT_ENTITY.getName(), 20, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.FLAT_TNT_ENTITY.getRegistryName(), SuperTNTMod.FLAT_TNT_ENTITY.getEntityClass(), SuperTNTMod.FLAT_TNT_ENTITY.getName(), 21, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.HOUSE_TNT_ENTITY.getRegistryName(), SuperTNTMod.HOUSE_TNT_ENTITY.getEntityClass(), SuperTNTMod.HOUSE_TNT_ENTITY.getName(), 22, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.MINE_TNT_ENTITY.getRegistryName(), SuperTNTMod.MINE_TNT_ENTITY.getEntityClass(), SuperTNTMod.MINE_TNT_ENTITY.getName(), 23, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.NOSTALGIA_TNT_ENTITY.getRegistryName(), SuperTNTMod.NOSTALGIA_TNT_ENTITY.getEntityClass(), SuperTNTMod.NOSTALGIA_TNT_ENTITY.getName(), 24, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SAVE_TNT_ENTITY.getRegistryName(), SuperTNTMod.SAVE_TNT_ENTITY.getEntityClass(), SuperTNTMod.SAVE_TNT_ENTITY.getName(), 25, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CRAP2_TNT_ENTITY.getRegistryName(), SuperTNTMod.CRAP2_TNT_ENTITY.getEntityClass(), SuperTNTMod.CRAP2_TNT_ENTITY.getName(), 26, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CLUSTER_TNT_ENTITY.getRegistryName(), SuperTNTMod.CLUSTER_TNT_ENTITY.getEntityClass(), SuperTNTMod.CLUSTER_TNT_ENTITY.getName(), 27, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SUPERCLUSTER_TNT_ENTITY.getRegistryName(), SuperTNTMod.SUPERCLUSTER_TNT_ENTITY.getEntityClass(), SuperTNTMod.SUPERCLUSTER_TNT_ENTITY.getName(), 28, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.HELL_TNT_ENTITY.getRegistryName(), SuperTNTMod.HELL_TNT_ENTITY.getEntityClass(), SuperTNTMod.HELL_TNT_ENTITY.getName(), 29, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.THUNDER_TNT_ENTITY.getRegistryName(), SuperTNTMod.THUNDER_TNT_ENTITY.getEntityClass(), SuperTNTMod.THUNDER_TNT_ENTITY.getName(), 30, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.TRUMP_TNT_ENTITY.getRegistryName(), SuperTNTMod.TRUMP_TNT_ENTITY.getEntityClass(), SuperTNTMod.TRUMP_TNT_ENTITY.getName(), 31, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.KIMJONG_TNT_ENTITY.getRegistryName(), SuperTNTMod.KIMJONG_TNT_ENTITY.getEntityClass(), SuperTNTMod.KIMJONG_TNT_ENTITY.getName(), 32, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.TREE_TNT_ENTITY.getRegistryName(), SuperTNTMod.TREE_TNT_ENTITY.getEntityClass(), SuperTNTMod.TREE_TNT_ENTITY.getName(), 33, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.FOREST_TNT_ENTITY.getRegistryName(), SuperTNTMod.FOREST_TNT_ENTITY.getEntityClass(), SuperTNTMod.FOREST_TNT_ENTITY.getName(), 34, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.LAVA_TNT_ENTITY.getRegistryName(), SuperTNTMod.LAVA_TNT_ENTITY.getEntityClass(), SuperTNTMod.LAVA_TNT_ENTITY.getName(), 35, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CRACK_TNT_ENTITY.getRegistryName(), SuperTNTMod.CRACK_TNT_ENTITY.getEntityClass(), SuperTNTMod.CRACK_TNT_ENTITY.getName(), 36, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.WEED_TNT_ENTITY.getRegistryName(), SuperTNTMod.WEED_TNT_ENTITY.getEntityClass(), SuperTNTMod.WEED_TNT_ENTITY.getName(), 37, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.WTF_TNT_ENTITY.getRegistryName(), SuperTNTMod.WTF_TNT_ENTITY.getEntityClass(), SuperTNTMod.WTF_TNT_ENTITY.getName(), 38, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.BUNKER_TNT_ENTITY.getRegistryName(), SuperTNTMod.BUNKER_TNT_ENTITY.getEntityClass(), SuperTNTMod.BUNKER_TNT_ENTITY.getName(), 39, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.ISLAND_TNT_ENTITY.getRegistryName(), SuperTNTMod.ISLAND_TNT_ENTITY.getEntityClass(), SuperTNTMod.ISLAND_TNT_ENTITY.getName(), 40, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.SINGULARITY_TNT_ENTITY.getRegistryName(), SuperTNTMod.SINGULARITY_TNT_ENTITY.getEntityClass(), SuperTNTMod.SINGULARITY_TNT_ENTITY.getName(), 41, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.PLEASENO_TNT_ENTITY.getRegistryName(), SuperTNTMod.PLEASENO_TNT_ENTITY.getEntityClass(), SuperTNTMod.PLEASENO_TNT_ENTITY.getName(), 42, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.WEATHER_TNT_ENTITY.getRegistryName(), SuperTNTMod.WEATHER_TNT_ENTITY.getEntityClass(), SuperTNTMod.WEATHER_TNT_ENTITY.getName(), 43, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.TIME_TNT_ENTITY.getRegistryName(), SuperTNTMod.TIME_TNT_ENTITY.getEntityClass(), SuperTNTMod.TIME_TNT_ENTITY.getName(), 44, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.RAKE_TNT_ENTITY.getRegistryName(), SuperTNTMod.RAKE_TNT_ENTITY.getEntityClass(), SuperTNTMod.RAKE_TNT_ENTITY.getName(), 45, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.LGBT_TNT_ENTITY.getRegistryName(), SuperTNTMod.LGBT_TNT_ENTITY.getEntityClass(), SuperTNTMod.LGBT_TNT_ENTITY.getName(), 46, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.CHEESE_TNT_ENTITY.getRegistryName(), SuperTNTMod.CHEESE_TNT_ENTITY.getEntityClass(), SuperTNTMod.CHEESE_TNT_ENTITY.getName(), 47, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.LAVAOCEAN_TNT_ENTITY.getRegistryName(), SuperTNTMod.LAVAOCEAN_TNT_ENTITY.getEntityClass(), SuperTNTMod.LAVAOCEAN_TNT_ENTITY.getName(), 48, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.TINYISLAND_TNT_ENTITY.getRegistryName(), SuperTNTMod.TINYISLAND_TNT_ENTITY.getEntityClass(), SuperTNTMod.TINYISLAND_TNT_ENTITY.getName(), 49, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.FACT_TNT_ENTITY.getRegistryName(), SuperTNTMod.FACT_TNT_ENTITY.getEntityClass(), SuperTNTMod.FACT_TNT_ENTITY.getName(), 50, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.ARROW_TNT_ENTITY.getRegistryName(), SuperTNTMod.ARROW_TNT_ENTITY.getEntityClass(), SuperTNTMod.ARROW_TNT_ENTITY.getName(), 51, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.AIRBORNE_TNT_ENTITY.getRegistryName(), SuperTNTMod.AIRBORNE_TNT_ENTITY.getEntityClass(), SuperTNTMod.AIRBORNE_TNT_ENTITY.getName(), 52, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.JAIL_TNT_ENTITY.getRegistryName(), SuperTNTMod.JAIL_TNT_ENTITY.getEntityClass(), SuperTNTMod.JAIL_TNT_ENTITY.getName(), 53, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.TELEPORT_TNT_ENTITY.getRegistryName(), SuperTNTMod.TELEPORT_TNT_ENTITY.getEntityClass(), SuperTNTMod.TELEPORT_TNT_ENTITY.getName(), 54, "supertnt", 128, 1, false);
            EntityRegistry.registerModEntity(SuperTNTMod.WARP_TNT_ENTITY.getRegistryName(), SuperTNTMod.WARP_TNT_ENTITY.getEntityClass(), SuperTNTMod.WARP_TNT_ENTITY.getName(), 55, "supertnt", 128, 1, false);
        }

        @SubscribeEvent
        public static void registerItemBlocks(Register<Item> event) {
            ItemBlock[] items = new ItemBlock[] { new ItemBlock(SuperTNTMod.WHATEVER_TEST), new ItemBlock(SuperTNTMod.CHEESE_BLOCK), new ItemBlock(SuperTNTMod.CHEESE_LEAVES), new ItemBlock(SuperTNTMod.CHEESE_GRASS), new ItemBlock(SuperTNTMod.CHEESE_BUSH), new ItemBlock(SuperTNTMod.EYETEST_BLOCK), new ItemBlock(SuperTNTMod.MOUTHTEST_BLOCK), new ItemBlock(SuperTNTMod.BlockLiquidPoop), new ItemBlock(SuperTNTMod.DIAMOND_GLASS), new ItemBlock(SuperTNTMod.POOP_BLOCK), new ItemBlock(SuperTNTMod.POOP_LEAVES), new ItemBlock(SuperTNTMod.LESBIAN_LEAVES), new ItemBlock(SuperTNTMod.CRAP_GRASS), new ItemBlock(SuperTNTMod.POOP_PLANT), new ItemBlock(SuperTNTMod.GAY_BUSH), new ItemBlock(SuperTNTMod.TRANS_GRASS), new ItemBlock(SuperTNTMod.PANSEXUAL_FLOWER), new ItemBlock(SuperTNTMod.NO_ANSWER), new ItemBlock(SuperTNTMod.YES_ANSWER), new ItemBlock(SuperTNTMod.LARGE_TNT), new ItemBlock(SuperTNTMod.MASSIVE_TNT), new ItemBlock(SuperTNTMod.SUPER_TNT), new ItemBlock(SuperTNTMod.DOOM_TNT), new ItemBlock(SuperTNTMod.END_TNT), new ItemBlock(SuperTNTMod.WTF_TNT), new ItemBlock(SuperTNTMod.SINGULARITY_TNT), new ItemBlock(SuperTNTMod.PLEASENO_TNT), new ItemBlock(SuperTNTMod.BIOME_TNT), new ItemBlock(SuperTNTMod.CLUSTER_TNT), new ItemBlock(SuperTNTMod.SUPERCLUSTER_TNT), new ItemBlock(SuperTNTMod.HELL_TNT), new ItemBlock(SuperTNTMod.FIRE_TNT), new ItemBlock(SuperTNTMod.SNOW_TNT), new ItemBlock(SuperTNTMod.OCEAN_TNT), new ItemBlock(SuperTNTMod.SPONGE_TNT), new ItemBlock(SuperTNTMod.LAVAOCEAN_TNT), new ItemBlock(SuperTNTMod.DIAMOND_TNT), new ItemBlock(SuperTNTMod.HOUSE_TNT), new ItemBlock(SuperTNTMod.BUNKER_TNT), new ItemBlock(SuperTNTMod.MOB_TNT), new ItemBlock(SuperTNTMod.MOB2_TNT), new ItemBlock(SuperTNTMod.MOB3_TNT), new ItemBlock(SuperTNTMod.NOMOB_TNT), new ItemBlock(SuperTNTMod.ARROW_TNT), new ItemBlock(SuperTNTMod.TREE_TNT), new ItemBlock(SuperTNTMod.FOREST_TNT), new ItemBlock(SuperTNTMod.TINYISLAND_TNT), new ItemBlock(SuperTNTMod.ISLAND_TNT), new ItemBlock(SuperTNTMod.NOSTALGIA_TNT), new ItemBlock(SuperTNTMod.EVERYTHING_TNT), new ItemBlock(SuperTNTMod.LGBT_TNT), new ItemBlock(SuperTNTMod.TRUMP_TNT), new ItemBlock(SuperTNTMod.KIMJONG_TNT), new ItemBlock(SuperTNTMod.CHRISTMAS_TNT), new ItemBlock(SuperTNTMod.CRAP_TNT), new ItemBlock(SuperTNTMod.CRAP2_TNT), new ItemBlock(SuperTNTMod.CHEESE_TNT), new ItemBlock(SuperTNTMod.FLAT_TNT), new ItemBlock(SuperTNTMod.MINE_TNT), new ItemBlock(SuperTNTMod.RAKE_TNT), new ItemBlock(SuperTNTMod.TIME_TNT), new ItemBlock(SuperTNTMod.WEATHER_TNT), new ItemBlock(SuperTNTMod.THUNDER_TNT), new ItemBlock(SuperTNTMod.CRACK_TNT), new ItemBlock(SuperTNTMod.WEED_TNT), new ItemBlock(SuperTNTMod.FACT_TNT), new ItemBlock(SuperTNTMod.CAVE_TNT), new ItemBlock(SuperTNTMod.SAVE_TNT), new ItemBlock(SuperTNTMod.WAVE_TNT), new ItemBlock(SuperTNTMod.AIRBORNE_TNT), new ItemBlock(SuperTNTMod.JAIL_TNT), new ItemBlock(SuperTNTMod.TELEPORT_TNT), new ItemBlock(SuperTNTMod.WARP_TNT), new ItemBlock(SuperTNTMod.DIAMONDNUKE_TNT), new ItemBlock(SuperTNTMod.LAVA_TNT)};
            IForgeRegistry registry = event.getRegistry();
            ItemBlock[] aitemblock = items;
            int i = items.length;

            for (int j = 0; j < i; ++j) {
                ItemBlock item = aitemblock[j];
                Block block = item.getBlock();
                ResourceLocation registryName = (ResourceLocation) Preconditions.checkNotNull(block.getRegistryName(), "Block %s has null registry name", block);

                registry.register(item.setRegistryName(registryName));
                RegistrationHandler.ITEM_BLOCKS.add(item);
            }

        }

        @SideOnly(Side.CLIENT)
        @SubscribeEvent
        public static void onRegisterModels(ModelRegistryEvent event) {
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WHATEVER_TEST), 0, new ModelResourceLocation(SuperTNTMod.WHATEVER_TEST.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHEESE_BLOCK), 0, new ModelResourceLocation(SuperTNTMod.CHEESE_BLOCK.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHEESE_GRASS), 0, new ModelResourceLocation(SuperTNTMod.CHEESE_GRASS.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHEESE_LEAVES), 0, new ModelResourceLocation(SuperTNTMod.CHEESE_LEAVES.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHEESE_BUSH), 0, new ModelResourceLocation(SuperTNTMod.CHEESE_BUSH.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.EYETEST_BLOCK), 0, new ModelResourceLocation(SuperTNTMod.EYETEST_BLOCK.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MOUTHTEST_BLOCK), 0, new ModelResourceLocation(SuperTNTMod.MOUTHTEST_BLOCK.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.BlockLiquidPoop), 0, new ModelResourceLocation(SuperTNTMod.BlockLiquidPoop.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.DIAMOND_GLASS), 0, new ModelResourceLocation(SuperTNTMod.DIAMOND_GLASS.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.POOP_BLOCK), 0, new ModelResourceLocation(SuperTNTMod.POOP_BLOCK.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.POOP_LEAVES), 0, new ModelResourceLocation(SuperTNTMod.POOP_LEAVES.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.LESBIAN_LEAVES), 0, new ModelResourceLocation(SuperTNTMod.LESBIAN_LEAVES.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CRAP_GRASS), 0, new ModelResourceLocation(SuperTNTMod.CRAP_GRASS.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.POOP_PLANT), 0, new ModelResourceLocation(SuperTNTMod.POOP_PLANT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.GAY_BUSH), 0, new ModelResourceLocation(SuperTNTMod.GAY_BUSH.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TRANS_GRASS), 0, new ModelResourceLocation(SuperTNTMod.TRANS_GRASS.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.PANSEXUAL_FLOWER), 0, new ModelResourceLocation(SuperTNTMod.PANSEXUAL_FLOWER.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.NO_ANSWER), 0, new ModelResourceLocation(SuperTNTMod.NO_ANSWER.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.YES_ANSWER), 0, new ModelResourceLocation(SuperTNTMod.YES_ANSWER.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.LARGE_TNT), 0, new ModelResourceLocation(SuperTNTMod.LARGE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MASSIVE_TNT), 0, new ModelResourceLocation(SuperTNTMod.MASSIVE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SUPER_TNT), 0, new ModelResourceLocation(SuperTNTMod.SUPER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.DOOM_TNT), 0, new ModelResourceLocation(SuperTNTMod.DOOM_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.END_TNT), 0, new ModelResourceLocation(SuperTNTMod.END_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WTF_TNT), 0, new ModelResourceLocation(SuperTNTMod.WTF_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SINGULARITY_TNT), 0, new ModelResourceLocation(SuperTNTMod.SINGULARITY_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.PLEASENO_TNT), 0, new ModelResourceLocation(SuperTNTMod.PLEASENO_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.BIOME_TNT), 0, new ModelResourceLocation(SuperTNTMod.BIOME_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CLUSTER_TNT), 0, new ModelResourceLocation(SuperTNTMod.CLUSTER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SUPERCLUSTER_TNT), 0, new ModelResourceLocation(SuperTNTMod.SUPERCLUSTER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.HELL_TNT), 0, new ModelResourceLocation(SuperTNTMod.HELL_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.FIRE_TNT), 0, new ModelResourceLocation(SuperTNTMod.FIRE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SNOW_TNT), 0, new ModelResourceLocation(SuperTNTMod.SNOW_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.OCEAN_TNT), 0, new ModelResourceLocation(SuperTNTMod.OCEAN_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SPONGE_TNT), 0, new ModelResourceLocation(SuperTNTMod.SPONGE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.LAVAOCEAN_TNT), 0, new ModelResourceLocation(SuperTNTMod.LAVAOCEAN_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.DIAMOND_TNT), 0, new ModelResourceLocation(SuperTNTMod.DIAMOND_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.HOUSE_TNT), 0, new ModelResourceLocation(SuperTNTMod.HOUSE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.BUNKER_TNT), 0, new ModelResourceLocation(SuperTNTMod.BUNKER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MOB_TNT), 0, new ModelResourceLocation(SuperTNTMod.MOB_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MOB2_TNT), 0, new ModelResourceLocation(SuperTNTMod.MOB2_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MOB3_TNT), 0, new ModelResourceLocation(SuperTNTMod.MOB3_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.NOMOB_TNT), 0, new ModelResourceLocation(SuperTNTMod.NOMOB_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.ARROW_TNT), 0, new ModelResourceLocation(SuperTNTMod.ARROW_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TREE_TNT), 0, new ModelResourceLocation(SuperTNTMod.TREE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.FOREST_TNT), 0, new ModelResourceLocation(SuperTNTMod.FOREST_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TINYISLAND_TNT), 0, new ModelResourceLocation(SuperTNTMod.TINYISLAND_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.ISLAND_TNT), 0, new ModelResourceLocation(SuperTNTMod.ISLAND_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.NOSTALGIA_TNT), 0, new ModelResourceLocation(SuperTNTMod.NOSTALGIA_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.EVERYTHING_TNT), 0, new ModelResourceLocation(SuperTNTMod.EVERYTHING_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.LGBT_TNT), 0, new ModelResourceLocation(SuperTNTMod.LGBT_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TRUMP_TNT), 0, new ModelResourceLocation(SuperTNTMod.TRUMP_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.KIMJONG_TNT), 0, new ModelResourceLocation(SuperTNTMod.KIMJONG_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHRISTMAS_TNT), 0, new ModelResourceLocation(SuperTNTMod.CHRISTMAS_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CRAP_TNT), 0, new ModelResourceLocation(SuperTNTMod.CRAP_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CRAP2_TNT), 0, new ModelResourceLocation(SuperTNTMod.CRAP2_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CHEESE_TNT), 0, new ModelResourceLocation(SuperTNTMod.CHEESE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.FLAT_TNT), 0, new ModelResourceLocation(SuperTNTMod.FLAT_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.MINE_TNT), 0, new ModelResourceLocation(SuperTNTMod.MINE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.RAKE_TNT), 0, new ModelResourceLocation(SuperTNTMod.RAKE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TIME_TNT), 0, new ModelResourceLocation(SuperTNTMod.TIME_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WEATHER_TNT), 0, new ModelResourceLocation(SuperTNTMod.WEATHER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.THUNDER_TNT), 0, new ModelResourceLocation(SuperTNTMod.THUNDER_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CRACK_TNT), 0, new ModelResourceLocation(SuperTNTMod.CRACK_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WEED_TNT), 0, new ModelResourceLocation(SuperTNTMod.WEED_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.FACT_TNT), 0, new ModelResourceLocation(SuperTNTMod.FACT_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.CAVE_TNT), 0, new ModelResourceLocation(SuperTNTMod.CAVE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.SAVE_TNT), 0, new ModelResourceLocation(SuperTNTMod.SAVE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WAVE_TNT), 0, new ModelResourceLocation(SuperTNTMod.WAVE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.AIRBORNE_TNT), 0, new ModelResourceLocation(SuperTNTMod.AIRBORNE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.JAIL_TNT), 0, new ModelResourceLocation(SuperTNTMod.JAIL_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.TELEPORT_TNT), 0, new ModelResourceLocation(SuperTNTMod.TELEPORT_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.WARP_TNT), 0, new ModelResourceLocation(SuperTNTMod.WARP_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.DIAMONDNUKE_TNT), 0, new ModelResourceLocation(SuperTNTMod.DIAMONDNUKE_TNT.getRegistryName(), "normal"));
            ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SuperTNTMod.LAVA_TNT), 0, new ModelResourceLocation(SuperTNTMod.LAVA_TNT.getRegistryName(), "normal"));
        }
    }
}
