modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="waterworld"
version="1.0.0"
displayName="Waterworld"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="wolfd, MCreator"

[[dependencies.waterworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




